server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # BACKEND_URL se inyecta como variable de entorno al arrancar el contenedor.
    # Docker Compose: http://backend:3000
    # Render: https://tp-integrador-devops.onrender.com
    location /api/ {
        proxy_pass            ${BACKEND_URL}/api/;
        proxy_http_version    1.1;
        proxy_ssl_server_name on;
        proxy_connect_timeout 120s;
        proxy_send_timeout    120s;
        proxy_read_timeout    120s;
        proxy_set_header      Host              $proxy_host;
        proxy_set_header      X-Real-IP         $remote_addr;
        proxy_set_header      X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
